version: '3'

networks:
  vmd:
    driver: bridge

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: vmd
    networks:
      - vmd
    ports:
      - 27017:27017
